2019-11-10 19:14:20.201266: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:14:20.203252: wfastcgi.py 3.0.0 initialized
2019-11-10 19:14:26.327135: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:14:26.345139: wfastcgi.py 3.0.0 initialized
iles in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:14:26.364143: wfastcgi.py 3.0.0 initialized
2019-11-10 19:19:28.482454: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:19:28.482454: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:19:28.491455: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:19:28.499457: wfastcgi.py 3.0.0 initialized
2019-11-10 19:19:28.508459: wfastcgi.py 3.0.0 initialized
2019-11-10 19:24:42.243602: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:24:42.264917: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:24:42.267922: Running on_exit tasks
2019-11-10 19:24:42.275923: wfastcgi.py 3.0.0 closed
2019-11-10 19:24:42.278940: wfastcgi.py 3.0.0 closed
2019-11-10 19:24:55.132470: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:24:55.153476: Running on_exit tasks
2019-11-10 19:24:55.174480: wfastcgi.py 3.0.0 closed
2019-11-10 19:27:37.242743: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:27:37.258747: Running on_exit tasks
2019-11-10 19:27:37.279752: wfastcgi.py 3.0.0 closed
2019-11-10 19:27:44.041934: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:27:44.043935: Running on_exit tasks
2019-11-10 19:27:44.046936: wfastcgi.py 3.0.0 closed
2019-11-10 19:27:50.132116: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:27:50.135116: Running on_exit tasks
2019-11-10 19:27:50.137117: wfastcgi.py 3.0.0 closed
2019-11-10 19:34:13.777529: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:34:13.797531: wfastcgi.py 3.0.0 initialized
2019-11-10 19:34:15.513918: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:34:15.535924: wfastcgi.py 3.0.0 initialized
2019-11-10 19:34:15.535924: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:34:15.546925: wfastcgi.py 3.0.0 initialized
2019-11-10 19:39:24.220267: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:39:24.240273: wfastcgi.py 3.0.0 initialized
2019-11-10 19:39:30.021367: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:39:30.041372: wfastcgi.py 3.0.0 initialized
2019-11-10 19:39:30.072379: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:39:30.088382: wfastcgi.py 3.0.0 initialized
2019-11-10 19:42:59.179302: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:42:59.189304: wfastcgi.py 3.0.0 initialized
2019-11-10 19:42:59.239316: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:42:59.250318: wfastcgi.py 3.0.0 initialized
2019-11-10 19:45:09.440343: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:45:14.559290: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:45:14.577295: wfastcgi.py 3.0.0 initialized
2019-11-10 19:45:16.301684: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:45:16.321688: wfastcgi.py 3.0.0 initialized
2019-11-10 19:45:16.377701: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:45:16.396705: wfastcgi.py 3.0.0 initialized
2019-11-10 19:50:28.443110: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:50:28.464751: Running on_exit tasks
2019-11-10 19:50:28.489779: wfastcgi.py 3.0.0 closed
2019-11-10 19:50:30.096454: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 19:50:30.117442: Running on_exit tasks
2019-11-10 19:50:30.138447: wfastcgi.py 3.0.0 closed
2019-11-10 19:50:36.663872: wfastcgi.py exiting because Recruitment\Recruitment\settings.py has changed, matching .*((\.py)|(\.config))$
2019-11-10 19:50:36.684879: Running on_exit tasks
2019-11-10 19:53:28.341182: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 19:53:28.363185: wfastcgi.py 3.0.0 initialized
2019-11-10 20:03:22.236825: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 20:03:22.238825: Running on_exit tasks
2019-11-10 20:03:22.239825: wfastcgi.py 3.0.0 closed
2019-11-10 20:06:18.471803: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 20:06:18.483805: wfastcgi.py 3.0.0 initialized
2019-11-10 20:16:47.378527: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 20:16:47.401536: Running on_exit tasks
2019-11-10 20:16:47.423539: wfastcgi.py 3.0.0 closed
2019-11-10 20:21:24.849327: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 20:21:24.879332: wfastcgi.py 3.0.0 initialized
2019-11-10 20:28:23.726343: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 20:28:23.728343: Running on_exit tasks
2019-11-10 20:28:23.729343: wfastcgi.py 3.0.0 closed
2019-11-10 20:35:22.061261: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 20:35:22.079265: wfastcgi.py 3.0.0 initialized
2019-11-10 20:40:35.928798: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 20:40:35.930799: Running on_exit tasks
2019-11-10 20:40:35.932798: wfastcgi.py 3.0.0 closed
2019-11-10 20:53:05.443989: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 20:53:05.460994: wfastcgi.py 3.0.0 initialized
2019-11-10 20:58:19.325383: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 20:58:19.328384: Running on_exit tasks
2019-11-10 20:58:19.330384: wfastcgi.py 3.0.0 closed
2019-11-10 22:13:15.144395: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 22:13:15.167179: wfastcgi.py 3.0.0 initialized
2019-11-10 22:19:03.647872: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 22:19:03.669878: Running on_exit tasks
2019-11-10 22:19:03.689882: wfastcgi.py 3.0.0 closed
2019-11-10 22:39:09.098624: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 22:39:09.121630: wfastcgi.py 3.0.0 initialized
2019-11-10 22:43:20.677893: wfastcgi.py exiting because Recruitment\applicantctl\models.py has changed, matching .*((\.py)|(\.config))$
2019-11-10 22:43:20.696897: Running on_exit tasks
2019-11-10 22:43:32.686444: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 22:43:32.706449: wfastcgi.py 3.0.0 initialized
2019-11-10 22:44:40.372229: wfastcgi.py exiting because Recruitment\applicantctl\models.py has changed, matching .*((\.py)|(\.config))$
2019-11-10 22:44:40.395234: Running on_exit tasks
2019-11-10 22:44:44.909305: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 22:44:44.919309: wfastcgi.py 3.0.0 initialized
2019-11-10 22:55:48.753217: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-10 22:55:48.775204: Running on_exit tasks
2019-11-10 22:55:48.790208: wfastcgi.py 3.0.0 closed
2019-11-10 22:56:19.367588: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 22:56:19.387593: wfastcgi.py 3.0.0 initialized
2019-11-10 22:58:54.969577: wfastcgi.py exiting because Recruitment\Recruitment\settings.py has changed, matching .*((\.py)|(\.config))$
2019-11-10 22:58:54.979581: Running on_exit tasks
2019-11-10 23:33:05.809640: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-10 23:33:05.820642: wfastcgi.py 3.0.0 initialized
2019-11-10 23:35:53.578825: wfastcgi.py exiting because Recruitment\Recruitment\settings.py has changed, matching .*((\.py)|(\.config))$
2019-11-10 23:35:53.581843: Running on_exit tasks
2019-11-11 00:09:55.475818: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-11 00:09:55.496821: wfastcgi.py 3.0.0 initialized
2019-11-11 00:16:19.371180: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-11 00:16:19.372180: Running on_exit tasks
2019-11-11 00:16:19.373181: wfastcgi.py 3.0.0 closed
2019-11-11 00:28:37.496689: wfastcgi.py will restart when files in C:\PycharmProjects3\ are changed: .*((\.py)|(\.config))$
2019-11-11 00:28:37.511819: wfastcgi.py 3.0.0 initialized
2019-11-11 00:33:51.384992: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\pycharmprojects3\venv\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-11-11 00:33:51.384992: Running on_exit tasks
2019-11-11 00:33:51.391016: wfastcgi.py 3.0.0 closed
